#!/usr/bin/awk -f

BEGIN {
    bits = 8
    for(x = 255; x >=0; x -= 2^i++)
        cidr[x] = bits--

    printf "Please enter current netmask: "
    getline netmask < "-"

    split(netmask, arr, "[.]")

    for(i = 1; i <= 4;i++)
        total += cidr[arr[i]]

    print total
}
